name: CI

on: [pull_request]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        pod install
        xcodebuild -workspace Legio.xcworkspace -scheme Legio -quiet CODE_SIGNING_ALLOWED="NO"
